stages:
  - build
  - deploy

build-docker-image:
  stage: build
  script: docker build --no-cache -t lvo.dev/keepitsimple prod

deploy-docker-image:
  stage: deploy
  script:
    - docker run -d --name keepitsimple --restart always lvo.dev/keepitsimple