version: "3"

services:

  nginx:
    image: nginx
    volumes:
      - ./blog/generated/public/:/usr/share/nginx/html/:cached
    ports:
      - 80:80

  hexo:
    build: dev
    volumes:
      - ./blog/:/blog/:cached
    ports:
      - "4000:4000"