# Header
menu:
  Accueil: /
  Archives: /archives
rss: /atom.xml
github: https://github.com/l-vo
logo_title: MyLogo
blog_title: Keep it simple. Stupid.

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: false
google_analytics: UA-116065119-1
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:

# hexo-generator-search config
search:
  path: search.xml
  field: post

# hexo-generator-seo-friendly-sitemap config
sitemap:
    path: sitemap.xml
