name: Deploy

on:
  push:
    branches: [master]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Docker buildx setup
        uses: docker/setup-buildx-action@v1
      - name: Docker repository login
        uses: docker/login-action@v1
        with:
          username: lvo9
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker repository build and push
        uses: docker/build-push-action@v2
        with:
          context: dev
          push: true
          tags: lvo9/keepitsimple
          cache-from: type=registry,ref=lvo9/keepitsimple:latest
          cache-to: type=inline
  generate-and-publish:
    needs: docker-build
    runs-on: ubuntu-latest
    container: lvo9/keepitsimple:latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Pages generation
        run: /run.sh generate
      - name: Upload to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          build_directory: blog/generated/public
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: dc2c77f4-2140-4795-85cd-3d619e661bdd
          NETLIFY_DEPLOY_TO_PROD: true

